import React from "react";
import { useNavigate } from "react-router-dom";
import ParticleBackground from "./ParticleBackground";
import ThemeToggle from "./ThemeToggle";
import { motion } from "framer-motion";

export default function LandingPage() {
  const navigate = useNavigate();

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.4 }}
      className="relative min-h-screen bg-[var(--bg)] text-[var(--text)] overflow-hidden"
    >
      <ParticleBackground />

      {/* Header */}
      <header className="relative z-10 flex justify-between items-center px-8 py-5 border-b border-gray-700 bg-[var(--bg)] bg-opacity-70">
        <div className="flex items-center space-x-3">
          
          <h1 className="text-2xl font-bold text-green-400 tracking-wide">Droxion</h1>
        </div>
        <nav className="flex space-x-4 items-center text-sm font-medium">
          <button onClick={() => navigate("/generator")} className="hover:text-green-400 transition">Generator</button>
          <button onClick={() => navigate("/plans")} className="hover:text-green-400 transition">Pricing</button>
          <button onClick={() => navigate("/login")} className="hover:text-green-400 transition">Login</button>
          <ThemeToggle />
        </nav>
      </header>

      {/* Hero Section */}
      <main className="relative z-10 flex flex-col items-center justify-center text-center px-6 py-20 md:py-28">
        <h2 className="text-4xl md:text-6xl font-extrabold mb-6 leading-tight tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-cyan-400 animate-fade-in">
          Create Stunning AI Reels in Seconds
        </h2>
        <p className="text-lg md:text-xl text-[var(--text-light)] max-w-2xl mb-10 animate-fade-in-slow">
          Script. Voice. Music. Captions. Everything done automatically for you by AI.
        </p>
        <button
          onClick={() => navigate("/generator")}
          className="bg-green-500 hover:bg-green-600 text-black px-8 py-4 text-lg font-bold rounded-full shadow-lg transition animate-bounce-slow"
        >
          🚀 Try It Free Now
        </button>
      </main>

      {/* Video Preview */}
      <section className="relative z-10 px-6 py-12 md:py-20 text-center">
        <h3 className="text-2xl font-bold mb-4">🎞 AI Reel Demo</h3>
        <p className="text-[var(--text-light)] mb-6">Watch a real video generated by Droxion in just 30 seconds.</p>
        <div className="mx-auto w-full max-w-xl aspect-video rounded-xl overflow-hidden shadow-xl border border-gray-700">
          <video src="/sample-reel.mp4" controls className="w-full h-full object-cover" />
        </div>
      </section>

      {/* Trusted By */}
      <section className="relative z-10 px-6 py-12 text-center border-y border-gray-800 bg-[var(--bg)]">
        <h4 className="text-lg text-[var(--text-light)] mb-6">Trusted by creators from</h4>
        <div className="flex justify-center flex-wrap gap-10 opacity-70 grayscale">
          <img src="/logo1.png" alt="Client" className="h-8" />
          <img src="/logo2.png" alt="Client" className="h-8" />
          <img src="/logo3.png" alt="Client" className="h-8" />
          <img src="/logo4.png" alt="Client" className="h-8" />
        </div>
      </section>

      {/* Testimonials */}
      <section className="relative z-10 px-6 py-16 text-center bg-[#0f172a]">
        <h3 className="text-2xl font-bold mb-8">💬 What Users Say</h3>
        <div className="grid gap-8 md:grid-cols-3 text-left text-sm text-[var(--text-light)] max-w-6xl mx-auto">
          <div className="bg-[#111827] p-6 rounded-xl shadow-md border border-gray-700">
            <p>“Droxion saved me 10+ hours per week. My reels look better than ever!”</p>
            <div className="mt-4 font-bold text-green-400">— Arjun M., Content Creator</div>
          </div>
          <div className="bg-[#111827] p-6 rounded-xl shadow-md border border-gray-700">
            <p>“As a solopreneur, this tool is a game changer. Everything is automatic.”</p>
            <div className="mt-4 font-bold text-green-400">— Priya S., Marketer</div>
          </div>
          <div className="bg-[#111827] p-6 rounded-xl shadow-md border border-gray-700">
            <p>“The AI voices and captions look so real. It’s like having an editing team.”</p>
            <div className="mt-4 font-bold text-green-400">— Zaid K., Influencer</div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 text-center py-6 text-sm text-[var(--text-light)] border-t border-gray-800 bg-[var(--bg)]">
        © {new Date().getFullYear()} Droxion. All rights reserved.
      </footer>
    </motion.div>
  );
}
